import os
from flask import Flask, render_template, request, redirect, flash, make_response
import fitz  # PyMuPDF
import re
from reportlab.pdfgen import canvas
from io import BytesIO

app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = 'uploads'
app.secret_key = 'your-secret-key-here'

APPROVED_COURSES = {
    r"(?i)living up to our commitments rcm training": "RCM",
    r"(?i)working in partnership with bt": "BT-PART",
    r"(?i)[^\w]don't[^\w]feed[^\w]the[^\w]'ish": "DFT"  # Updated pattern for DFT
}

def extract_certificate_data(text):
    """Improved extraction with multiple pattern attempts"""
    patterns = [
        # Pattern 1: Standard BT format
        {
            'name': re.compile(r"certificate of completion.*?This is to certify that\s*(.*?)\s*has completed", re.DOTALL|re.IGNORECASE),
            'course': re.compile(r"has completed\s*(.*?)\s*on", re.DOTALL|re.IGNORECASE),
            'date': re.compile(r"on\s*(\d{1,2}/\d{1,2}/\d{4})")
        },
        # Pattern 2: Alternative format
        {
            'name': re.compile(r"certificate.*?awarded to\s*(.*?)\s*for", re.DOTALL|re.IGNORECASE),
            'course': re.compile(r"for\s*(.*?)\s*completed", re.DOTALL|re.IGNORECASE),
            'date': re.compile(r"completed on\s*(\d{1,2}/\d{1,2}/\d{4})")
        }
    ]

    for pattern in patterns:
        try:
            name_match = pattern['name'].search(text)
            course_match = pattern['course'].search(text)
            date_match = pattern['date'].search(text)
            
            if name_match and course_match:
                return {
                    'name': name_match.group(1).strip(),
                    'course': course_match.group(1).strip(),
                    'date': date_match.group(1) if date_match else None
                }
        except Exception:
            continue
    
    return None

def verify_certificate(pdf_path):
    try:
        doc = fitz.open(pdf_path)
        text = ""
        for page in doc:
            text += page.get_text()

        data = extract_certificate_data(text)
        if not data:
            return None

        # Check if course matches any approved pattern
        course_title = data['course']
        course_code = None
        
        for pattern, code in APPROVED_COURSES.items():
            if re.search(pattern, course_title, re.IGNORECASE):
                course_code = code
                break

        if not course_code:
            return None

        return {
            "course_title": course_title,
            "course_code": course_code,
            "completion_date": data['date'] or "Date not available",
            "filename": os.path.basename(pdf_path)
        }

    except Exception as e:
        print(f"Error processing {pdf_path}: {str(e)}")
        return None

def generate_verification_pdf(verified_courses):
    buffer = BytesIO()
    p = canvas.Canvas(buffer)
    
    # PDF styling
    p.setFont("Helvetica-Bold", 16)
    p.drawString(100, 800, "BT Certificate Verification Report")
    p.setFont("Helvetica", 12)
    p.drawString(100, 770, "The following BT certificates have been verified:")
    
    y_position = 730
    for course in verified_courses:
        p.drawString(100, y_position, f"• {course['course_title']} ({course['course_code']})")
        p.drawString(120, y_position-20, f"Completed: {course['completion_date']}")
        p.drawString(120, y_position-40, f"File: {course['filename']}")
        y_position -= 70
    
    p.setFont("Helvetica-Oblique", 10)
    p.drawString(100, 50, "Generated by BT Certificate Verification System")
    
    p.showPage()
    p.save()
    buffer.seek(0)
    return buffer

@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        files = [
            request.files.get('pdf_file_1'),
            request.files.get('pdf_file_2'),
            request.files.get('pdf_file_3')
        ]

        verified_courses = []
        invalid_files = []

        for file in [f for f in files if f and f.filename]:
            if not file.filename.lower().endswith('.pdf'):
                invalid_files.append(file.filename)
                continue

            try:
                os.makedirs(app.config['UPLOAD_FOLDER'], exist_ok=True)
                file_path = os.path.join(app.config['UPLOAD_FOLDER'], file.filename)
                file.save(file_path)
                
                result = verify_certificate(file_path)
                if result:
                    verified_courses.append(result)
                else:
                    invalid_files.append(file.filename)
            except Exception as e:
                invalid_files.append(file.filename)
                flash(f"Error processing {file.filename}: {str(e)}", "error")

        if verified_courses:
            try:
                pdf_buffer = generate_verification_pdf(verified_courses)
                response = make_response(pdf_buffer.getvalue())
                response.headers['Content-Type'] = 'application/pdf'
                response.headers['Content-Disposition'] = 'inline; filename=bt_verification_report.pdf'
                return response
            except Exception as e:
                flash(f"Failed to generate PDF report: {str(e)}", "error")
        elif invalid_files:
            flash("No valid BT certificates found in the uploaded files. Please check:", "error")
            for filename in invalid_files:
                flash(f"- {filename}", "error")
        else:
            flash("No valid files were uploaded", "error")

        return redirect(request.url)

    return render_template('index.html')

if __name__ == '__main__':
    os.makedirs(app.config['UPLOAD_FOLDER'], exist_ok=True)
    app.run(host='0.0.0.0', port=5000, debug=True)
