apiVersion: v1
kind: Service
metadata:
  name: pdf-scanner
spec:
  type: {{ .Values.service.type }}
  selector:
    app: pdf-scanner
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
