name: Build, Push, and Deploy to EKS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/pdf-scanner:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/pdf-scanner:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Update kubeconfig for EKS
      run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Create namespace if not exists
      run: kubectl create namespace default --dry-run=client -o yaml | kubectl apply -f -

    - name: Update Helm dependencies
      run: helm dependency update ./helm-chart

    - name: Deploy using Helm
      run: helm upgrade --install pdf-scanner ./helm-chart --namespace default

    - name: Show Service Info
      run: kubectl get svc pdf-scanner -o wide
